##############################################
#
# 发布阶段-配置文件
#
##############################################

proxy:
  enabled: true
  server: @proxy_server@

spring:
  ####################
  # 关系数据库设置
  ####################
  datasource:
    # 数据库连接
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    url: @datasource_url@
    username: @datasource_username@
    password: @datasource_password@

  ####################
  # mongodb
  ####################
  data:
    mongodb:
      host: @mongodb_host@
      port: @mongodb_port@
      username: @mongodb_username@
      password: @mongodb_password@
      database: @mongodb_database@
      authenticationDatabase: admin

####################
# neo4j
####################
neo4j:
  uri: @neo4j_url@
  user: @neo4j_username@
  password: @neo4j_password@

####################
# gstore
####################
gstore:
  uri: 172.19.41.246
  port: 3305
  dbname: adb
  toggle: false

####################
# 设置领域和领域本体
####################
#下面是国防工业风格
#cihai:
#  domainId: 284
#  ontologyId: 160
#下面是辞海风格
cihai:
  domainId: 230
  ontologyId: 106

####################
# 自动化抽取
####################
automatic:
  # 服务器
  ftp:
    username: root
    password: 1
    host: 172.19.36.40
    port: 21
    destDir: automatic
  server: http://172.19.41.246
  relationPort: 12345
  entityPort: 11111
  classifyPort: 12355

####################
# 机器学习模型所需要的初始阈值
####################
threshold:
  label: 10000
  entity: 10000
  relation: 10000
  labelStep: 10
  entityStep: 10
  relationStep: 10